image: python:lastest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
    paths:
        - .cache/pip
        - venv/
before_script:
    - uname -a
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv ext/venv
    - source ext/venv/bin/activate
    - pip install ipykernel jupyter_client pynvim

test:
    script:
        - nvim -N --noplugin -u <(\cat << VIMRC                                                                              00:13:41
          let g:python3_host_prog='./ext/venv/bin/python'
          set rtp+=./ext/vader.vim
          source ./ext/vader.vim/plugin/vader.vim
          set rtp+=.
          source ./plugin/deuterium.vim
          VIMRC) -c 'Vader! test/*.vader' > /dev/null

