image: docker:latest

services:
    - docker:dind

stages:
    - build
    - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
    stage: build
    before_script:
        - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    script:
        - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest .
        - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
    after_script:
        - docker logout ${CI_REGISTRY}

test:
    stage: test
    before_script:
        - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
    script:
        - docker run ${CI_REGISTRY}/${CI_PROJECT_PATH}
    after_script:
        - docker logout ${CI_REGISTRY}
